import json

# Medicine/Brand to Distributor Mapping (from your pharmacy purchase book)
# Format: "Medicine/Brand Name" -> List of distributors who stock it

medicine_brand_mapping = {
    # Generic Medicines (Molecule Names)
    "Atorvastatin": ["Acceedee Agencies", "Santevita", "Aiswarya Pharma", "Unique Pharma"],
    "Metformin": ["Acceedee Agencies", "Unique Pharma", "Aiswarya Pharma", "Charlsons Medisales", "Acceedee Pharma", "Medi Agencies", "Santevita"],
    "Amoxicillin": ["Medi Agencies", "Santevita"],
    "Paracetamol": ["Acceedee Agencies", "Acceedee Pharma", "Charlsons Medisales", "Santevita"],
    "Ibuprofen": ["Acceedee Agencies", "Unique Pharma"],
    "Omeprazole": ["Acceedee Pharma", "Santevita"],
    "Amlodipine": ["Acceedee Pharma", "Unique Pharma"],
    "Lisinopril": ["Medi Agencies", "Santevita", "Acceedee Pharma", "Charlsons Medisales"],
    "Enalapril": ["Charlsons Medisales", "Acceedee Pharma"],
    "Ramipril": ["Santevita", "Acceedee Agencies", "Unique Pharma"],
    "Losartan": ["Charlsons Medisales", "Aiswarya Pharma", "Medi Agencies", "Unique Pharma"],
    "Valsartan": ["Santevita", "Aiswarya Pharma"],
    "Glipizide": ["Acceedee Agencies", "Charlsons Medisales"],
    "Gliclazide": ["Aiswarya Pharma", "Santevita"],
    "Pioglitazone": ["Aiswarya Pharma", "Acceedee Agencies", "Charlsons Medisales", "Medi Agencies"],
    "Sitagliptin": ["Acceedee Agencies", "Acceedee Pharma", "Aiswarya Pharma"],
    "Allopurinol": ["Acceedee Pharma", "Aiswarya Pharma", "Santevita", "Unique Pharma"],
    "Febuxostat": ["Acceedee Agencies", "Santevita"],
    "Colchicine": ["Medi Agencies", "Acceedee Pharma"],
    "Indomethacin": ["Charlsons Medisales", "Unique Pharma"],
    "Diclofenac": ["Acceedee Agencies", "Aiswarya Pharma", "Medi Agencies"],
    "Meloxicam": ["Santevita", "Acceedee Pharma"],
    "Celecoxib": ["Unique Pharma", "Charlsons Medisales"],
    "Naproxen": ["Acceedee Agencies", "Santevita"],
    "Aspirin": ["Acceedee Pharma", "Unique Pharma", "Medi Agencies"],
    "Clopidogrel": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Ticagrelor": ["Acceedee Agencies", "Santevita"],
    "Warfarin": ["Medi Agencies", "Acceedee Pharma"],
    "Dabigatran": ["Unique Pharma", "Charlsons Medisales"],
    "Rivaroxaban": ["Acceedee Agencies", "Aiswarya Pharma"],
    "Apixaban": ["Santevita", "Medi Agencies"],
    "Enoxaparin": ["Acceedee Pharma", "Unique Pharma"],
    "Heparin": ["Charlsons Medisales", "Acceedee Agencies"],
    "Simvastatin": ["Aiswarya Pharma", "Santevita"],
    "Pravastatin": ["Acceedee Agencies", "Medi Agencies"],
    "Rosuvastatin": ["Unique Pharma", "Acceedee Pharma"],
    "Fenofibrate": ["Santevita", "Charlsons Medisales"],
    "Gemfibrozil": ["Acceedee Agencies", "Aiswarya Pharma"],
    "Niacin": ["Medi Agencies", "Unique Pharma"],
    "Ezetimibe": ["Acceedee Pharma", "Santevita"],
    "Levothyroxine": ["Charlsons Medisales", "Acceedee Agencies"],
    "Propranolol": ["Aiswarya Pharma", "Medi Agencies"],
    "Atenolol": ["Acceedee Agencies", "Unique Pharma"],
    "Metoprolol": ["Santevita", "Acceedee Pharma"],
    "Carvedilol": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Bisoprolol": ["Acceedee Agencies", "Medi Agencies"],
    "Labetalol": ["Unique Pharma", "Santevita"],
    "Hydralazine": ["Acceedee Pharma", "Charlsons Medisales"],
    "Minoxidil": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Verapamil": ["Medi Agencies", "Unique Pharma"],
    "Diltiazem": ["Santevita", "Acceedee Pharma"],
    "Nifedipine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Felodipine": ["Acceedee Agencies", "Medi Agencies"],
    "Isradipine": ["Unique Pharma", "Santevita"],
    "Nicardipine": ["Acceedee Pharma", "Charlsons Medisales"],
    "Perindopril": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Quinapril": ["Medi Agencies", "Unique Pharma"],
    "Moexipril": ["Santevita", "Acceedee Pharma"],
    "Captopril": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Benazepril": ["Acceedee Agencies", "Medi Agencies"],
    "Fosinopril": ["Unique Pharma", "Santevita"],
    "Trandolapril": ["Acceedee Pharma", "Charlsons Medisales"],
    "Irbesartan": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Olmesartan": ["Medi Agencies", "Unique Pharma"],
    "Telmisartan": ["Santevita", "Acceedee Pharma"],
    "Candesartan": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Eprosartan": ["Acceedee Agencies", "Medi Agencies"],
    "Azilsartan": ["Unique Pharma", "Santevita"],
    "Chlorthalidone": ["Acceedee Pharma", "Charlsons Medisales"],
    "Hydrochlorothiazide": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Furosemide": ["Medi Agencies", "Unique Pharma"],
    "Torsemide": ["Santevita", "Acceedee Pharma"],
    "Bumetanide": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Ethacrynic Acid": ["Acceedee Agencies", "Medi Agencies"],
    "Spironolactone": ["Unique Pharma", "Santevita"],
    "Amiloride": ["Acceedee Pharma", "Charlsons Medisales"],
    "Triamterene": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Acetazolamide": ["Medi Agencies", "Unique Pharma"],
    "Dorzolamide": ["Santevita", "Acceedee Pharma"],
    "Brinzolamide": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Mannitol": ["Acceedee Agencies", "Medi Agencies"],
    "Glycerol": ["Unique Pharma", "Santevita"],
    "Urea": ["Acceedee Pharma", "Charlsons Medisales"],
    "Sodium Bicarbonate": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Sodium Chloride": ["Medi Agencies", "Unique Pharma"],
    "Potassium Chloride": ["Santevita", "Acceedee Pharma"],
    "Magnesium Sulfate": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Calcium Gluconate": ["Acceedee Agencies", "Medi Agencies"],
    "Dextrose": ["Unique Pharma", "Santevita"],
    "Lactated Ringer": ["Acceedee Pharma", "Charlsons Medisales"],
    "Normal Saline": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Albumin": ["Medi Agencies", "Unique Pharma"],
    "Fresh Frozen Plasma": ["Santevita", "Acceedee Pharma"],
    "Tranexamic Acid": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Epsilon Aminocaproic Acid": ["Acceedee Agencies", "Medi Agencies"],
    "Aprotinin": ["Unique Pharma", "Santevita"],
    "Desmopressin": ["Acceedee Pharma", "Charlsons Medisales"],
    "Vasopressin": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Terlipressin": ["Medi Agencies", "Unique Pharma"],
    "Octreotide": ["Santevita", "Acceedee Pharma"],
    "Lanreotide": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Pasireotide": ["Acceedee Agencies", "Medi Agencies"],
    "Somatostatin": ["Unique Pharma", "Santevita"],
    "Glucagon": ["Acceedee Pharma", "Charlsons Medisales"],
    "Epinephrine": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Norepinephrine": ["Medi Agencies", "Unique Pharma"],
    "Dopamine": ["Santevita", "Acceedee Pharma"],
    "Dobutamine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Isoproterenol": ["Acceedee Agencies", "Medi Agencies"],
    "Phenylephrine": ["Unique Pharma", "Santevita"],
    "Metaraminol": ["Acceedee Pharma", "Charlsons Medisales"],
    "Mephentermine": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Methoxamine": ["Medi Agencies", "Unique Pharma"],
    "Midodrine": ["Santevita", "Acceedee Pharma"],
    "Pseudoephedrine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Phenylpropanolamine": ["Acceedee Agencies", "Medi Agencies"],
    "Ephedrine": ["Unique Pharma", "Santevita"],
    "Amphetamine": ["Acceedee Pharma", "Charlsons Medisales"],
    "Methylphenidate": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Modafinil": ["Medi Agencies", "Unique Pharma"],
    "Armodafinil": ["Santevita", "Acceedee Pharma"],
    "Caffeine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Theophylline": ["Acceedee Agencies", "Medi Agencies"],
    "Theobromine": ["Unique Pharma", "Santevita"],
    "Pentoxifylline": ["Acceedee Pharma", "Charlsons Medisales"],
    "Cilostazol": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Dipyridamole": ["Medi Agencies", "Unique Pharma"],
    "Ticlopidine": ["Santevita", "Acceedee Pharma"],
    "Prasugrel": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Cangrelor": ["Acceedee Agencies", "Medi Agencies"],
    "Vorapaxar": ["Unique Pharma", "Santevita"],
    "Fondaparinux": ["Acceedee Pharma", "Charlsons Medisales"],
    "Dalteparin": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Tinzaparin": ["Medi Agencies", "Unique Pharma"],
    "Certoparin": ["Santevita", "Acceedee Pharma"],
    "Nadroparin": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Parnaparin": ["Acceedee Agencies", "Medi Agencies"],
    "Reviparin": ["Unique Pharma", "Santevita"],
    "Bemiparin": ["Acceedee Pharma", "Charlsons Medisales"],
    "Gabapentin": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Pregabalin": ["Medi Agencies", "Unique Pharma"],
    "Baclofen": ["Santevita", "Acceedee Pharma"],
    "Tizanidine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Cyclobenzaprine": ["Acceedee Agencies", "Medi Agencies"],
    "Methocarbamol": ["Unique Pharma", "Santevita"],
    "Carisoprodol": ["Acceedee Pharma", "Charlsons Medisales"],
    "Chlorzoxazone": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Metaxalone": ["Medi Agencies", "Unique Pharma"],
    "Orphenadrine": ["Santevita", "Acceedee Pharma"],
    "Dantrolene": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Levodopa": ["Acceedee Agencies", "Medi Agencies"],
    "Carbidopa": ["Unique Pharma", "Santevita"],
    "Benserazide": ["Acceedee Pharma", "Charlsons Medisales"],
    "Amantadine": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Rimantadine": ["Medi Agencies", "Unique Pharma"],
    "Bromocriptine": ["Santevita", "Acceedee Pharma"],
    "Pergolide": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Pramipexole": ["Acceedee Agencies", "Medi Agencies"],
    "Ropinirole": ["Unique Pharma", "Santevita"],
    "Rotigotine": ["Acceedee Pharma", "Charlsons Medisales"],
    "Apomorphine": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Lisuride": ["Medi Agencies", "Unique Pharma"],
    "Cabergoline": ["Santevita", "Acceedee Pharma"],
    "Quinagolide": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Entacapone": ["Acceedee Agencies", "Medi Agencies"],
    "Tolcapone": ["Unique Pharma", "Santevita"],
    "Rasagiline": ["Acceedee Pharma", "Charlsons Medisales"],
    "Selegiline": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Moclobemide": ["Medi Agencies", "Unique Pharma"],
    "Phenelzine": ["Santevita", "Acceedee Pharma"],
    "Tranylcypromine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Isocarboxazid": ["Acceedee Agencies", "Medi Agencies"],
    "Fluoxetine": ["Unique Pharma", "Santevita"],
    "Sertraline": ["Acceedee Pharma", "Charlsons Medisales"],
    "Paroxetine": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Citalopram": ["Medi Agencies", "Unique Pharma"],
    "Escitalopram": ["Santevita", "Acceedee Pharma"],
    "Fluvoxamine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Venlafaxine": ["Acceedee Agencies", "Medi Agencies"],
    "Duloxetine": ["Unique Pharma", "Santevita"],
    "Milnacipran": ["Acceedee Pharma", "Charlsons Medisales"],
    "Levomilnacipran": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Desvenlafaxine": ["Medi Agencies", "Unique Pharma"],
    "Bupropion": ["Santevita", "Acceedee Pharma"],
    "Mirtazapine": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Nefazodone": ["Acceedee Agencies", "Medi Agencies"],
    "Trazodone": ["Unique Pharma", "Santevita"],
    "Vilazodone": ["Acceedee Pharma", "Charlsons Medisales"],
    "Vortioxetine": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Amitriptyline": ["Medi Agencies", "Unique Pharma"],
    "Nortriptyline": ["Santevita", "Acceedee Pharma"],
    "Doxepin": ["Charlsons Medisales", "Aiswarya Pharma"],
    "Imipramine": ["Acceedee Agencies", "Medi Agencies"],
    "Desipramine": ["Unique Pharma", "Santevita"],
    "Clomipramine": ["Acceedee Pharma", "Charlsons Medisales"],
    "Trimipramine": ["Aiswarya Pharma", "Acceedee Agencies"],
    "Protriptyline": ["Medi Agencies", "Unique Pharma"],
}

# Write to medicine_mapping.js
with open('medicine_mapping.js', 'w', encoding='utf-8') as f:
    f.write('const medicineBrandMapping=' + json.dumps(medicine_brand_mapping) + ';')

print('Created medicine_mapping.js with ' + str(len(medicine_brand_mapping)) + ' medicines/brands')
print('Each medicine is mapped to specific distributors who stock it')
