[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm run web"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { REACT_APP_API_URL = "https://medicine-distributor-api.herokuapp.com/api" }

[context.deploy-preview]
  environment = { REACT_APP_API_URL = "http://localhost:5000/api" }

[context.branch-deploy]
  environment = { REACT_APP_API_URL = "http://localhost:5000/api" }
